base_url = "https://vuongkienthanh.github.io"
title = "Bác sĩ Vương Kiến Thanh"
description = "Blog cá nhân của BS Vương Kiến Thanh"

compile_sass = false
minify_html = true
generate_feeds = false
build_search_index = false

theme = "anemone"
default_language = "vn"

taxonomies = [{ name = "tags", feed = false }]

[slugify]
paths = "safe"
taxonomies = "on"
anchors = "on"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false

[extra]
author = "Vương Kiến Thanh"
display_author = true
list_pages = false
default_theme = "light"
twitter_card = false
favicon = "favicon.ico"
image = ""

header_nav = [
    { url = "/", name_vn = "/Bản thân/" },
    { url = "/team", name_vn = "/Team/" },
    { url = "/wiki", name_vn = "/wiki/" },
]
